---
# set_SELINUX_to_enforcing/tasks/main.yml

- name: 'Set SELINUX state to enforcing'
  ansible.posix.selinux:
    state: 'enforcing'
    policy: "{{ selinux_policy }}"
  notify:
    - 'Reboot'
    - 'Wait for the machine(s) to be ready again'

- name: 'Flush handlers to trigger reboot now'
  ansible.builtin.meta: flush_handlers

- name: 'Check output of getenforce after reboot'
  ansible.builtin.shell: 'getenforce'
  register: 'getenforce_output'
  failed_when: '"Enforcing" not in getenforce_output.stdout'
  changed_when: 'false'
